Document: rtpbreak
Title: Debian rtpbreak Manual
Author: <insert document author here>
Abstract: This manual describes what rtpbreak is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rtpbreak/rtpbreak.sgml.gz

Format: postscript
Files: /usr/share/doc/rtpbreak/rtpbreak.ps.gz

Format: text
Files: /usr/share/doc/rtpbreak/rtpbreak.text.gz

Format: HTML
Index: /usr/share/doc/rtpbreak/html/index.html
Files: /usr/share/doc/rtpbreak/html/*.html
